#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build embedded data asset for flow-canvas-audit demo.

Reads the real UCI audit-risk business dataset (E:\\数据\\04-审计数据集与基准
\\Audit-Risk-Classification\\audit_risk.csv), computes a deterministic
source fingerprint, and emits a self-contained JS asset so the demo can
re-compute every statistic inside the browser.  Stdlib only; no network.
"""
from __future__ import annotations

import csv
import hashlib
import json
import math
from datetime import datetime, timezone
from pathlib import Path

SOURCE = Path(r"E:\数据\04-审计数据集与基准\Audit-Risk-Classification\audit_risk.csv")
OUT = Path(__file__).with_name("flow-canvas-audit.data.js")

HEADER_ALIASES = {"Score_B": "Score_B2", "Prob": "Prob2"}  # duplicate names in source


def to_num(raw: str) -> float | None:
    v = raw.strip()
    if v == "" or v.lower() in ("na", "nan", "null", "-"):
        return None
    try:
        f = float(v)
    except ValueError:
        return None
    return f if math.isfinite(f) else None


def main() -> None:
    raw_bytes = SOURCE.read_bytes()
    sha = hashlib.sha256(raw_bytes).hexdigest()

    with SOURCE.open("r", newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.reader(fh))
    seen = {}
    header = []
    for h in rows[0]:
        name = HEADER_ALIASES.get(h.strip(), h.strip())
        seen[name] = seen.get(name, 0) + 1
        header.append(name if seen[name] == 1 else f"{name}__{seen[name]}")

    records = [[to_num(c) for c in r] for r in rows[1:] if r and any(c.strip() for c in r)]

    payload = {
        "provenance": {
            "source": str(SOURCE),
            "dataset": "UCI Audit Data Set (audit_risk.csv)",
            "sha256": sha,
            "rows": len(records),
            "cols": len(header),
            "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        },
        "columns": header,
        "records": records,
    }

    OUT.write_text(
        "// AUTO-GENERATED by build_data.py — do not edit by hand.\n"
        + "window.AUDIT_DEMO_DATA = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.name}: {len(records)} rows x {len(header)} cols, sha256={sha[:16]}…")
    print("columns:", ", ".join(header))


if __name__ == "__main__":
    main()