#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build embedded multi-source data asset for flow-canvas-audit-pro demo.

Reads SIX real business datasets under E:\\数据 (each kept byte-identical),
computes a deterministic sha256 fingerprint per source, and emits one
self-contained JS asset so the demo re-computes every statistic inside the
browser (zero backend / zero network / zero side effects).  Stdlib only.
"""
from __future__ import annotations

import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

OUT = Path(__file__).with_name("flow-canvas-audit-pro.data.js")

# (embedded key, short display name, absolute source path)
SOURCES: list[tuple[str, str, Path]] = [
    ("ledger", "audit-system raw_transactions.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\projects\audit-system\data\raw_transactions.csv")),
    ("expense", "ai-anomaly-detection expense_ledger.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\skills\ai-anomaly-detection\evals\files\expense_ledger.csv")),
    ("bank_stmt", "automated-reconciliation bank_statement.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\skills\automated-reconciliation\evals\files\bank_statement.csv")),
    ("gl_cash", "automated-reconciliation gl_cash.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\skills\automated-reconciliation\evals\files\gl_cash.csv")),
    ("bank_dirty", "automated-reconciliation bank_dirty.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\skills\automated-reconciliation\evals\files\bank_dirty.csv")),
    ("controls", "audit-checklist control_register.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\skills\audit-checklist\evals\files\control_register.csv")),
    ("pay", "forensic-accounting disbursements.csv",
     Path(r"E:\数据\03-AI审计技能包\financeskills\skills\forensic-accounting\evals\files\disbursements.csv")),
    ("baseline", "UCI Audit Data Set audit_risk.csv",
     Path(r"E:\数据\04-审计数据集与基准\Audit-Risk-Classification\audit_risk.csv")),
]

# UCI audit_risk.csv carries duplicated column names — make them unique.
BASELINE_ALIASES = {"Score_B": "Score_B2", "Prob": "Prob2"}


def to_num(v: str) -> float | str | int | None:
    """Deterministic cell conversion: number where possible, else keep text."""
    s = v.strip()
    if not s:
        return None
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        return s


def load(path: Path, aliases: dict[str, str] | None = None) -> tuple[str, list[str], list[list]]:
    """Return (sha256, header, records) for one CSV."""
    raw = path.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    with path.open("r", newline="", encoding="utf-8-sig") as fh:
        rows = list(csv.reader(fh))
    seen: dict[str, int] = {}
    header: list[str] = []
    for h in rows[0]:
        name = (aliases or {}).get(h.strip(), h.strip())
        seen[name] = seen.get(name, 0) + 1
        header.append(name if seen[name] == 1 else f"{name}__{seen[name]}")
    records = [
        [to_num(c) for c in r]
        for r in rows[1:]
        if r and any(c.strip() for c in r)
    ]
    return sha, header, records


def main() -> None:
    payload: dict = {
        "sources": {},
        "prov": {"generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                 "root": r"E:\数据", "count": len(SOURCES)},
    }
    for key, label, path in SOURCES:
        sha, header, records = load(path, BASELINE_ALIASES if key == "baseline" else None)
        payload["sources"][key] = {
            "file": str(path),
            "label": label,
            "sha256": sha,
            "cols": header,
            "rows": len(records),
            "records": records,
        }
    OUT.write_text(
        "// AUTO-GENERATED by build_data.py — do not edit by hand.\n"
        + "window.AUDIT_PRO_DATA = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    total = sum(s["rows"] for s in payload["sources"].values())
    print(f"ok: {len(payload['sources'])} sources, {total} records total -> {OUT}")


if __name__ == "__main__":
    main()