"""Audit 100-plugin network specs (contract design, ComfyUI-style per-plugin folders).

Layers / stages:
  foundation  = 数据支撑层 18
  mandate/risk/plan/field/evidence/finding/report/remedy = 核心业务循环层 76 (8 阶段)
  govern      = 治理优化层 6

Each entry: (n, slug, name, cap, kind, layer, stage, ins, outs, desc)
  ins/outs: list of (contract_id, version, format, delivery, classification, schema_ref, max_bytes|None)
  desc: business description incl. link semantics (upstream/downstream/calls).

Side effects: all read_only (shadow planning; nothing writes domain tables).
"""

SCHEMA = {
    "artifact": ("artifact-ref.schema.json", "application/json", 256 * 1024 * 1024),
    "ledger": ("ledger-artifact-ref.schema.json", "application/json", 256 * 1024 * 1024),
    "quality-candidates": ("audit-quality-candidates.schema.json", "application/json", 64 * 1024 * 1024),
    "anomaly-candidates": ("anomaly-candidates.schema.json", "application/json", 64 * 1024 * 1024),
    "finding-draft": ("finding-draft.schema.json", "application/json", 16 * 1024 * 1024),
    "plan-draft": ("investigation-plan-draft.schema.json", "application/json", 16 * 1024 * 1024),
    "report-draft": ("report-draft.schema.json", "application/json", 16 * 1024 * 1024),
    "workpaper": ("workpaper-export.schema.json", "application/json", 64 * 1024 * 1024),
    "evidence-lineage": ("evidence-lineage.schema.json", "application/json", 16 * 1024 * 1024),
    "dataset-validation": ("dataset-validation.schema.json", "application/json", 4 * 1024 * 1024),
    "metric-series": ("metric-series.schema.json", "application/json", 16 * 1024 * 1024),
    "workflow": ("workflow.schema.json", "application/json", 4 * 1024 * 1024),
    "document": ("document-content.schema.json", "application/json", 64 * 1024 * 1024),
    "graph-candidates": ("graph-candidate-set.schema.json", "application/json", 32 * 1024 * 1024),
    "proposal-draft": ("graph-proposal-draft.schema.json", "application/json", 16 * 1024 * 1024),
    "retention": ("retention-recommendation.schema.json", "application/json", 4 * 1024 * 1024),
}

# (contract_id, version, format, delivery, classification, schema_key)
def C(cid: str, key: str, ver: str = "1.0.0", fmt: str = "artifact_ref",
      delivery: str = "reference", cls: str = "audit_confidential") -> tuple:
    schema_name, _content_type, max_bytes = SCHEMA[key]
    return {
        "contract_id": cid, "version": ver, "format": fmt, "delivery": delivery,
        "classification": cls, "schema_ref": schema_name,
        "max_bytes": max_bytes,
    }


def J(cid: str, key: str, ver: str = "1.0.0", cls: str = "audit_confidential") -> tuple:
    schema_name, _content_type, max_bytes = SCHEMA[key]
    return {
        "contract_id": cid, "version": ver, "format": "json",
        "delivery": "request_response", "classification": cls,
        "schema_ref": schema_name, "max_bytes": max_bytes,
    }


# ---------------------------------------------------------------- foundation 18
FOUNDATION = [
    (1, "multi-source-collect", "多源数据采集", "audit.foundation.collect", "ingestion",
     [C("audit-source-request", "artifact")], [J("audit-source-set", "document")],
     "对接财务/业务/OA/外部监管多系统数据；被凭证穿透、风险扫描、疑点核查类插件调用（⇢ 上层调用本层）。"),
    (2, "finance-clean", "财务数据清洗", "audit.foundation.finance-clean", "analysis",
     [C("raw-finance-set", "artifact")], [J("clean-finance-set", "ledger")],
     "对凭证、账簿、报表去重/补全/标准化；被财务异常预警、问题金额计算、底稿勾稽校验调用（⇢）。"),
    (3, "biz-standardize", "业务数据标准化", "audit.foundation.biz-standardize", "analysis",
     [C("raw-biz-set", "artifact")], [J("standard-biz-set", "dataset-validation")],
     "统一采购、销售、人力业务口径；被内控测绘、流程断点、资产盘点调用（⇢）。"),
    (4, "master-mapping", "主数据映射", "audit.foundation.master-mapping", "analysis",
     [C("master-source", "artifact")], [J("master-map", "dataset-validation")],
     "统一科目/供应商/员工/资产编码；被责任认定、跨系统比对、往来函证调用（⇢）。"),
    (5, "lineage-track", "数据血缘追踪", "audit.foundation.lineage-track", "graph",
     [C("lineage-query", "artifact")], [J("lineage-graph", "evidence-lineage")],
     "记录数据采集到应用全链路流转；被证据真实性校验、问题溯源、底稿复核调用（⇢）。"),
    (6, "data-mask", "数据脱敏", "audit.foundation.data-mask", "governance",
     [C("mask-request", "artifact")], [J("masked-set", "artifact")],
     "敏感数据自动脱敏；⊣ 穿透所有数据展示与对外输出节点。"),
    (7, "data-encrypt", "数据加密存储", "audit.foundation.data-encrypt", "governance",
     [C("encrypt-request", "artifact")], [J("encrypted-ref", "artifact")],
     "底稿/证据等核心数据加密存储；⊣ 穿透所有归档存储节点。"),
    (8, "metadata-manage", "元数据管理", "audit.foundation.metadata-manage", "governance",
     [C("metadata-query", "artifact")], [J("metadata-dict", "dataset-validation")],
     "统一数据字典、指标定义；被所有指标计算、数据分析类插件调用（⇢）。"),
    (9, "quality-check", "数据质量校验", "audit.foundation.quality-check", "analysis",
     [C("quality-input", "artifact")], [J("quality-report", "dataset-validation")],
     "核查完整性/准确性/一致性；被资料预检、报告数据校验、底稿校验调用（⇢）。"),
    (10, "metric-compute", "统一指标计算", "audit.foundation.metric-compute", "analysis",
     [C("metric-input", "artifact")], [J("metric-output", "metric-series")],
     "内置审计指标库自动计算财务/业务/风险指标；被风险评估、疑点识别、优先级排序调用（⇢）。"),
    (11, "tag-manage", "标签体系管理", "audit.foundation.tag-manage", "governance",
     [C("tag-query", "artifact")], [J("tag-tree", "dataset-validation")],
     "管理审计对象/问题/风险标签；被立项打标、证据分类、问题分级、案例入库调用（⇢）。"),
    (12, "fulltext-search", "全文检索引擎", "audit.foundation.fulltext-search", "retrieval",
     [C("search-query", "artifact")], [J("search-hits", "document")],
     "海量文档/凭证关键词检索；被底稿、证据、问题核查类插件调用（⇢）。"),
    (13, "ocr-extract", "OCR 识别", "audit.foundation.ocr-extract", "ingestion",
     [C("ocr-image", "artifact")], [J("ocr-text", "document")],
     "识别纸质单据、发票、合同文字；被取证、底稿、核验类插件调用（⇢）。"),
    (14, "nlp-process", "自然语言处理", "audit.foundation.nlp-process", "analysis",
     [C("nlp-input", "artifact")], [J("nlp-output", "document")],
     "文本摘要、语义匹配、自动撰写；被报告、访谈、规则匹配类插件调用（⇢）。"),
    (15, "rule-engine", "规则引擎配置", "audit.foundation.rule-engine", "governance",
     [C("rule-input", "artifact")], [J("rule-evaluation", "dataset-validation")],
     "可视化配置审计规则、校验逻辑；被风险预警、疑点识别、定性复核类插件调用（⇢）。"),
    (16, "viz-analysis", "可视化分析", "audit.foundation.viz-analysis", "visualization",
     [C("viz-input", "metric-series")], [J("viz-output", "artifact")],
     "生成图表、看板、热图；被风险热图、趋势分析、成果看板、质量评分调用（⇢）。"),
    (17, "workflow-engine", "工作流引擎", "audit.foundation.workflow-engine", "workflow",
     [C("workflow-request", "artifact")], [J("workflow-state", "workflow")],
     "驱动各类审批、流转流程；⊣ 穿透所有审批、流转、派单节点。"),
    (18, "permission-control", "权限管控", "audit.foundation.permission-control", "governance",
     [C("access-request", "artifact")], [J("access-decision", "dataset-validation")],
     "基于角色配置数据/功能访问权限；⊣ 穿透所有插件访问控制。"),
]

# ---------------------------------------------------------------- business 76
BUSINESS = [
    # stage 1 mandate 立项 10
    (19, "demand-collect", "审计需求征集", "audit.mandate.demand-collect", "analysis", "mandate",
     [C("demand-input", "artifact")], [J("demand-set", "document")],
     "面向管理层/业务部门征集审计需求；上游治理层输入，下游输出至立项申报，调用标签体系（⇢）。"),
    (20, "strategy-align", "战略目标对齐", "audit.mandate.strategy-align", "analysis", "mandate",
     [C("demand-set", "document")], [J("aligned-demand", "document")],
     "需求与公司战略、年度重点对标；上游需求征集，下游输出至立项评审。"),
    (21, "annual-propose", "年度立项申报", "audit.mandate.annual-propose", "analysis", "mandate",
     [C("aligned-demand", "document")], [J("proposal-set", "document")],
     "立项申请与材料填报；上游需求对齐结果，下游输出至立项评审。"),
    (22, "proposal-score", "立项评审打分", "audit.mandate.proposal-score", "analysis", "mandate",
     [C("proposal-set", "document")], [J("scored-proposal", "metric-series")],
     "按预设维度对立项申请评分排序；上游立项申报，调用工作流引擎驱动评审（⇢）。"),
    (23, "project-library", "项目库管理", "audit.mandate.project-library", "analysis", "mandate",
     [C("scored-proposal", "metric-series")], [J("project-snapshot", "dataset-validation")],
     "存储备选与立项项目全生命周期；上游评审通过项目，下游输出至计划编制，并同步全流程各阶段状态（网状）。"),
    (24, "priority-rank", "项目优先级排序", "audit.mandate.priority-rank", "analysis", "mandate",
     [C("project-snapshot", "dataset-validation")], [J("priority-order", "metric-series")],
     "基于风险/重要性/资源匹配度排序；上游项目库，调用统一指标计算权重（⇢）。"),
    (25, "notice-generate", "审计通知书生成", "audit.mandate.notice-generate", "analysis", "mandate",
     [C("project-snapshot", "dataset-validation")], [J("audit-notice", "document")],
     "自动生成标准化审计通知书并下发；上游正式立项项目，调用 NLP 生成文本（⇢）。"),
    (26, "material-submit", "被审单位资料报送", "audit.mandate.material-submit", "ingestion", "mandate",
     [C("notice-accept", "artifact")], [J("submitted-material", "artifact")],
     "在线收集被审单位前置资料；上游通知书下发，下游输出至资料预检。"),
    (27, "material-precheck", "前置资料预检", "audit.mandate.material-precheck", "analysis", "mandate",
     [C("submitted-material", "artifact")], [J("precheck-report", "dataset-validation")],
     "自动校验报送资料完整合规；上游资料报送，调用数据质量校验（⇢）。"),
    (28, "team-forming", "项目组建与分工", "audit.mandate.team-forming", "workflow", "mandate",
     [C("project-snapshot", "dataset-validation")], [J("team-scheme", "workflow")],
     "配置审计组人员/角色/分工；上游正式立项项目，调用权限管控分配权限（⇢）。"),
    # stage 2 risk 风险 11
    (29, "policy-risk-scan", "宏观政策风险扫描", "audit.risk.policy-risk-scan", "analysis", "risk",
     [C("policy-input", "artifact")], [J("policy-risk-set", "anomaly-candidates")],
     "匹配最新监管政策识别合规风险；调用规则引擎与外部政策数据，输出至风险矩阵。"),
    (30, "industry-benchmark", "行业风险对标", "audit.risk.industry-benchmark", "analysis", "risk",
     [C("industry-input", "artifact")], [J("industry-risk-set", "anomaly-candidates")],
     "对标同行业风险事件识别潜在风险；调用外部对标数据，输出至风险矩阵。"),
    (31, "internal-control-map", "内控流程风险测绘", "audit.risk.internal-control-map", "analysis", "risk",
     [C("submitted-material", "artifact")], [J("ic-risk-set", "anomaly-candidates")],
     "遍历内控流程识别控制缺陷与断点；上游前置资料，调用业务数据标准化，输出至风险矩阵。"),
    (32, "finance-anomaly-alert", "财务异常指标预警", "audit.risk.finance-anomaly-alert", "analysis", "risk",
     [C("clean-finance-set", "ledger")], [J("finance-anomaly-set", "anomaly-candidates")],
     "计算财务指标偏离度识别异常波动；调用统一指标计算，输出至风险矩阵。"),
    (33, "process-gap-detect", "业务流程断点识别", "audit.risk.process-gap-detect", "analysis", "risk",
     [C("standard-biz-set", "dataset-validation")], [J("process-gap-set", "anomaly-candidates")],
     "扫描采购/销售/资金流程异常节点；调用业务数据标准化，输出至风险矩阵。"),
    (34, "fraud-pattern-match", "舞弊风险特征匹配", "audit.risk.fraud-pattern-match", "analysis", "risk",
     [C("risk-input-set", "artifact")], [J("fraud-risk-set", "anomaly-candidates")],
     "基于舞弊三角模型匹配异常特征；调用规则引擎，输出至风险矩阵。"),
    (35, "risk-matrix-build", "风险矩阵生成", "audit.risk.risk-matrix-build", "visualization", "risk",
     [C("policy-risk-set", "anomaly-candidates"), C("industry-risk-set", "anomaly-candidates"),
      C("ic-risk-set", "anomaly-candidates"), C("finance-anomaly-set", "anomaly-candidates"),
      C("process-gap-set", "anomaly-candidates"), C("fraud-risk-set", "anomaly-candidates")],
     [J("risk-matrix", "metric-series")],
     "汇总各类风险点生成影响-概率矩阵；上游 6 类风险扫描，下游输出至风险等级赋值。"),
    (36, "risk-level-assign", "风险等级赋值", "audit.risk.risk-level-assign", "analysis", "risk",
     [C("risk-matrix", "metric-series")], [J("risk-level-set", "metric-series")],
     "对风险点自动打分定级（高/中/低）；上游风险矩阵，调用规则引擎。"),
    (37, "high-risk-locate", "高风险领域定位", "audit.risk.high-risk-locate", "analysis", "risk",
     [C("risk-level-set", "metric-series")], [J("high-risk-area", "metric-series")],
     "筛选高风险点对应业务领域/流程节点；上游风险等级结果，下游输出至方案编制。"),
    (38, "risk-heatmap", "风险热图绘制", "audit.risk.risk-heatmap", "visualization", "risk",
     [C("risk-level-set", "metric-series")], [J("risk-heatmap", "artifact")],
     "可视化呈现风险分布；上游风险等级结果，调用可视化分析。"),
    (39, "risk-response-advice", "风险应对建议生成", "audit.risk.risk-response-advice", "analysis", "risk",
     [C("high-risk-area", "metric-series")], [J("risk-advice-set", "document")],
     "针对高风险点匹配应对策略与审计重点；上游高风险领域，调用 NLP；直接输入方案编制阶段（跨阶段直连）。"),
    # stage 3 plan 计划 9
    (40, "annual-plan-build", "年度审计计划编制", "audit.plan.annual-plan-build", "analysis", "plan",
     [C("priority-order", "metric-series")], [J("annual-plan", "document")],
     "整合全年项目生成年度审计计划；上游项目优先级排序，输出至审批流程。"),
    (41, "project-scheme-build", "项目审计方案编制", "audit.plan.project-scheme-build", "analysis", "plan",
     [C("high-risk-area", "metric-series"), C("risk-advice-set", "document")],
     [J("project-scheme", "document")],
     "编制审计范围/重点/程序；上游高风险领域与应对建议，调用审计程序模板。"),
    (42, "program-template-match", "审计程序模板匹配", "audit.plan.program-template-match", "retrieval", "plan",
     [C("scheme-request", "document")], [J("program-template", "document")],
     "匹配标准审计程序库；上游方案需求，输出至方案编制。"),
    (43, "sampling-select", "审计抽样", "audit.plan.sampling-select", "analysis", "plan",
     [C("sampling-input", "artifact")], [J("sampling-plan", "dataset-validation")],
     "根据审计目标与总体特征选择抽样方法；上游审计程序，调用统计计算能力。"),
    (44, "sample-size-compute", "样本量自动计算", "audit.plan.sample-size-compute", "analysis", "plan",
     [C("sampling-plan", "dataset-validation")], [J("sample-size", "metric-series")],
     "基于置信水平/偏差率计算样本规模；上游抽样方法，输出至现场实施。"),
    (45, "staff-schedule", "审计人员排班", "audit.plan.staff-schedule", "workflow", "plan",
     [C("team-scheme", "workflow")], [J("schedule-plan", "workflow")],
     "根据项目需求/人员技能匹配排班；上游项目分工，调用人力资源数据。"),
    (46, "effort-budget", "工时预算管理", "audit.plan.effort-budget", "analysis", "plan",
     [C("schedule-plan", "workflow")], [J("effort-budget", "metric-series")],
     "编制各阶段工时预算与成本测算；上游人员排班，输出至进度管控。"),
    (47, "resource-conflict-detect", "资源冲突检测", "audit.plan.resource-conflict-detect", "analysis", "plan",
     [C("schedule-plan", "workflow"), C("project-snapshot", "dataset-validation")],
     [J("conflict-alert", "dataset-validation")],
     "识别人员跨项目冲突并预警；上游排班结果，调用项目库数据。"),
    (48, "plan-version-control", "计划版本管控", "audit.plan.plan-version-control", "governance", "plan",
     [C("plan-change", "document")], [J("plan-version", "workflow")],
     "管理计划与方案多版本变更；上游计划变更申请，调用工作流引擎。"),
    # stage 4 field 实施 14
    (49, "site-checkin-track", "现场签到与轨迹", "audit.field.site-checkin-track", "ingestion", "field",
     [C("checkin-input", "artifact")], [J("checkin-log", "metric-series")],
     "记录审计人员现场出勤与轨迹；上游人员排班，输出至审计日志。"),
    (50, "workpaper-build", "审计底稿编制", "audit.field.workpaper-build", "analysis", "field",
     [C("program-template", "document"), C("sample-size", "metric-series")],
     [J("workpaper-draft", "workpaper")],
     "按审计程序编制底稿；上游程序模板与样本，调用全文检索、OCR。"),
    (51, "voucher-drilldown", "凭证穿透查询", "audit.field.voucher-drilldown", "retrieval", "field",
     [C("clean-finance-set", "ledger")], [J("voucher-chain", "ledger")],
     "从报表直达明细账、凭证原始单据；上游财务数据，调用多源数据采集。"),
    (52, "confirm-letter", "往来款函证", "audit.field.confirm-letter", "workflow", "field",
     [C("confirm-input", "artifact")], [J("confirm-result", "workflow")],
     "生成函证/跟踪回函/统计结果；上游往来款审计程序，调用工作流引擎。"),
    (53, "inventory-count", "存货监盘", "audit.field.inventory-count", "analysis", "field",
     [C("inventory-input", "artifact")], [J("inventory-result", "dataset-validation")],
     "制定监盘计划/记录结果/识别盘盈盘亏；上游存货审计程序，调用数据比对。"),
    (54, "asset-check", "固定资产盘点", "audit.field.asset-check", "analysis", "field",
     [C("asset-input", "artifact")], [J("asset-result", "dataset-validation")],
     "匹配资产台账与实物；上游资产审计程序，调用 OCR 识别。"),
    (55, "interview-record", "访谈记录管理", "audit.field.interview-record", "ingestion", "field",
     [C("interview-input", "artifact")], [J("interview-note", "document")],
     "记录访谈提纲/内容/要点；上游审计程序，调用 NLP 整理纪要。"),
    (56, "meeting-minutes", "会议纪要自动整理", "audit.field.meeting-minutes", "analysis", "field",
     [C("meeting-audio", "artifact")], [J("meeting-minutes", "document")],
     "会商录音转写并提炼要点；调用语音转写与 NLP，输出至底稿。"),
    (57, "cross-dept-inquiry", "跨部门数据协查", "audit.field.cross-dept-inquiry", "workflow", "field",
     [C("inquiry-request", "artifact")], [J("inquiry-result", "workflow")],
     "发起跨部门数据调取与核实；调用工作流引擎，输出至证据归集。"),
    (58, "suspicion-flag", "疑点实时标记", "audit.field.suspicion-flag", "analysis", "field",
     [C("field-finding-input", "artifact")], [J("suspicion-set", "anomaly-candidates")],
     "对现场疑点即时标记分类；上游现场执行过程，下游输出至疑点汇总。"),
    (59, "evidence-photo", "现场取证拍照上传", "audit.field.evidence-photo", "ingestion", "field",
     [C("photo-input", "artifact")], [J("photo-evidence", "artifact")],
     "上传取证照片并关联底稿；调用 OCR 识别，输出至证据管理。"),
    (60, "audit-log", "审计日志自动记录", "audit.field.audit-log", "governance", "field",
     [C("log-event", "artifact")], [J("audit-log-set", "workflow")],
     "全程自动记录所有审计操作与数据访问；⊣ 穿透全现场阶段，调用权限管控。"),
    (61, "progress-report", "进度实时填报", "audit.field.progress-report", "analysis", "field",
     [C("effort-budget", "metric-series")], [J("progress-daily", "metric-series")],
     "每日填报项目进度与完成工时；上游工时预算，输出至项目管控。"),
    (62, "extension-approve", "延期申请审批", "audit.field.extension-approve", "workflow", "field",
     [C("extension-request", "document")], [J("extension-decision", "workflow")],
     "处理延期/程序调整审批；调用工作流引擎，同步更新计划版本。"),
    # stage 5 evidence 证据底稿 10
    (63, "evidence-archive", "证据分类归档", "audit.evidence.evidence-archive", "analysis", "evidence",
     [C("evidence-input", "artifact")], [J("evidence-index", "evidence-lineage")],
     "按类型/程序分类归集证据；上游现场取证结果，调用标签体系。"),
    (64, "evidence-verify", "证据真实性校验", "audit.evidence.evidence-verify", "analysis", "evidence",
     [C("evidence-index", "evidence-lineage")], [J("evidence-verdict", "dataset-validation")],
     "交叉验证证据一致真实；上游证据归档，调用数据血缘追踪。"),
    (65, "workpaper-reconcile", "底稿勾稽关系校验", "audit.evidence.workpaper-reconcile", "analysis", "evidence",
     [C("workpaper-draft", "workpaper")], [J("reconcile-report", "dataset-validation")],
     "自动校验底稿间数据勾稽、逻辑一致；上游底稿编制，调用规则引擎。"),
    (66, "workpaper-review3", "底稿三级复核", "audit.evidence.workpaper-review3", "workflow", "evidence",
     [C("reconcile-report", "dataset-validation")], [J("review3-verdict", "workflow")],
     "驱动编制人-项目经理-部门负责人三级复核；调用工作流引擎，贯穿底稿全周期。"),
    (67, "workpaper-version-diff", "底稿版本对比", "audit.evidence.workpaper-version-diff", "analysis", "evidence",
     [C("workpaper-change", "workpaper")], [J("version-diff", "dataset-validation")],
     "对比不同版本底稿修改痕迹；上游底稿变更，调用版本管理能力。"),
    (68, "evidence-index-link", "证据索引关联", "audit.evidence.evidence-index-link", "graph", "evidence",
     [C("workpaper-draft", "workpaper"), C("evidence-index", "evidence-lineage")],
     [J("evidence-link-graph", "evidence-lineage")],
     "建立底稿与证据索引关联，双向穿透查询；上游底稿与证据。"),
    (69, "workpaper-template-update", "底稿模板更新", "audit.evidence.workpaper-template-update", "analysis", "evidence",
     [C("standard-update", "document")], [J("workpaper-template", "document")],
     "根据最新准则更新底稿模板；上游准则更新，输出至模板库。"),
    (70, "e-signature", "电子签章", "audit.evidence.e-signature", "governance", "evidence",
     [C("review3-verdict", "workflow")], [J("signed-workpaper", "workpaper")],
     "对复核通过底稿/证据加盖电子签章；调用身份认证，输出至正式档案。"),
    (71, "workpaper-borrow-approve", "底稿借阅审批", "audit.evidence.workpaper-borrow-approve", "workflow", "evidence",
     [C("borrow-request", "artifact")], [J("borrow-decision", "workflow")],
     "管理底稿借阅/复制审批；调用工作流、权限管控。"),
    (72, "workpaper-encrypt-store", "底稿加密存储", "audit.evidence.workpaper-encrypt-store", "governance", "evidence",
     [C("signed-workpaper", "workpaper")], [J("archived-workpaper", "artifact")],
     "正式底稿加密归档；调用数据加密，实现长期存档。"),
    # stage 6 finding 定性 8
    (73, "suspicion-merge", "审计疑点汇总", "audit.finding.suspicion-merge", "analysis", "finding",
     [C("suspicion-set", "anomaly-candidates"), C("photo-evidence", "artifact")],
     [J("merged-suspicion", "anomaly-candidates")],
     "汇总全流程疑点去重分类；上游现场疑点标记与取证，下游输出至问题核实。"),
    (74, "issue-type-judge", "问题性质判定", "audit.finding.issue-type-judge", "analysis", "finding",
     [C("merged-suspicion", "anomaly-candidates")], [J("issue-type-set", "finding-draft")],
     "初步判定问题类型（合规/财务/内控/舞弊）；上游疑点汇总，调用规则引擎。"),
    (75, "violation-clause-match", "违规条款匹配", "audit.finding.violation-clause-match", "retrieval", "finding",
     [C("issue-type-set", "finding-draft")], [J("violation-clause", "finding-draft")],
     "自动匹配监管法规/公司制度条款；上游问题性质，调用法规库数据。"),
    (76, "issue-amount-compute", "问题金额计算", "audit.finding.issue-amount-compute", "analysis", "finding",
     [C("issue-verify-input", "finding-draft"), C("clean-finance-set", "ledger")],
     [J("issue-amount", "finding-draft")],
     "自动核算问题金额/税款/损失；上游问题核实与财务数据。"),
    (77, "responsible-party-find", "责任主体认定", "audit.finding.responsible-party-find", "analysis", "finding",
     [C("issue-trace-input", "finding-draft"), C("master-map", "dataset-validation")],
     [J("responsible-party", "finding-draft")],
     "追溯问题对应责任部门/岗位/人员；上游问题流程溯源，调用主数据。"),
    (78, "issue-grade", "问题分级分类", "audit.finding.issue-grade", "analysis", "finding",
     [C("issue-amount", "finding-draft"), C("responsible-party", "finding-draft")],
     [J("graded-issue", "finding-draft")],
     "按严重程度/影响范围分级；上游金额与责任认定，调用分级标准。"),
    (79, "auditee-feedback", "被审单位意见反馈", "audit.finding.auditee-feedback", "workflow", "finding",
     [C("graded-issue", "finding-draft")], [J("feedback-set", "finding-draft")],
     "发起问题确认收集被审单位反馈；调用工作流引擎，输出至异议核实。"),
    (80, "issue-final-review", "问题定性复核", "audit.finding.issue-final-review", "analysis", "finding",
     [C("feedback-set", "finding-draft")], [J("final-issue-set", "finding-draft")],
     "最终复核问题定性分级；上游意见反馈，输出至报告；直接追溯现场审计日志与访谈记录（跨阶段）。"),
    # stage 7 report 报告 7
    (81, "report-frame-build", "报告框架自动生成", "audit.report.report-frame-build", "analysis", "report",
     [C("project-snapshot", "dataset-validation")], [J("report-frame", "report-draft")],
     "根据项目类型匹配报告框架；上游项目信息，调用报告模板库。"),
    (82, "issue-desc-write", "问题描述自动撰写", "audit.report.issue-desc-write", "analysis", "report",
     [C("final-issue-set", "finding-draft")], [J("issue-desc", "report-draft")],
     "基于问题信息生成标准化描述；上游问题定性结果，调用 NLP。"),
    (83, "advice-match", "审计建议匹配", "audit.report.advice-match", "retrieval", "report",
     [C("final-issue-set", "finding-draft")], [J("advice-set", "report-draft")],
     "针对问题类型匹配审计建议；上游问题清单，调用最佳实践库。"),
    (84, "report-data-check", "报告数据校验", "audit.report.report-data-check", "analysis", "report",
     [C("report-draft-input", "report-draft")], [J("report-check-report", "dataset-validation")],
     "校验报告中数据/口径一致；上游报告初稿，调用数据质量校验。"),
    (85, "report-multi-review", "报告多级审核", "audit.report.report-multi-review", "workflow", "report",
     [C("report-check-report", "dataset-validation")], [J("report-approved", "report-draft")],
     "驱动报告多级审批与修改；调用工作流引擎，同步管理版本。"),
    (86, "result-distill", "审计成果提炼", "audit.report.result-distill", "analysis", "report",
     [C("report-approved", "report-draft")], [J("distilled-result", "document")],
     "提炼共性发现与管理启示；上游正式报告，输出至成果库。"),
    (87, "notice-mask-publish", "公告信息脱敏发布", "audit.report.notice-mask-publish", "governance", "report",
     [C("report-approved", "report-draft")], [J("published-notice", "document")],
     "报告脱敏后对内发布；调用数据脱敏，输出至公示节点。"),
    # stage 8 remedy 整改 7
    (88, "remedy-dispatch", "整改任务派单", "audit.remedy.remedy-dispatch", "workflow", "remedy",
     [C("final-issue-set", "finding-draft")], [J("remedy-task", "workflow")],
     "问题拆解为整改任务派发责任主体；上游正式报告问题清单，调用工作流引擎。"),
    (89, "remedy-plan-review", "整改方案审核", "audit.remedy.remedy-plan-review", "workflow", "remedy",
     [C("remedy-task", "workflow")], [J("remedy-plan-approved", "workflow")],
     "审核责任单位整改方案；上游整改派单，调用审批流程。"),
    (90, "remedy-progress-track", "整改进度跟踪", "audit.remedy.remedy-progress-track", "analysis", "remedy",
     [C("remedy-plan-approved", "workflow")], [J("remedy-progress", "metric-series")],
     "实时跟踪整改执行进度；上游整改方案，自动预警逾期。"),
    (91, "remedy-effect-verify", "整改成效验证", "audit.remedy.remedy-effect-verify", "analysis", "remedy",
     [C("remedy-evidence", "artifact"), C("evidence-index", "evidence-lineage")],
     [J("remedy-verdict", "dataset-validation")],
     "核实整改证据验证有效性；上游整改提交，调用证据校验；直接调取底稿/证据历史资料（跨阶段）。"),
    (92, "remedy-overdue-alert", "逾期整改预警", "audit.remedy.remedy-overdue-alert", "analysis", "remedy",
     [C("remedy-progress", "metric-series")], [J("overdue-alert", "metric-series")],
     "超期未完成整改自动预警；上游进度跟踪，调用消息通知。"),
    (93, "remedy-close", "整改销号管理", "audit.remedy.remedy-close", "workflow", "remedy",
     [C("remedy-verdict", "dataset-validation")], [J("remedy-ledger", "workflow")],
     "验证通过任务销号；上游成效验证，输出至整改台账。"),
    (94, "remedy-publish", "整改结果公示", "audit.remedy.remedy-publish", "governance", "remedy",
     [C("remedy-ledger", "workflow")], [J("published-remedy", "document")],
     "对内公示整改完成情况；调用数据脱敏，接受全员监督。"),
]

# ---------------------------------------------------------------- govern 6
GOVERN = [
    (95, "project-quality-score", "审计项目质量评分", "audit.govern.project-quality-score", "analysis",
     [C("project-flow-input", "artifact")], [J("quality-score", "metric-series")],
     "按质量标准量化评分全项目流程/成果；上游全流程数据，输出至质量考核。"),
    (96, "effect-evaluate", "审计成效量化评估", "audit.govern.effect-evaluate", "analysis",
     [C("remedy-ledger", "workflow")], [J("effect-report", "metric-series")],
     "从整改/管理提升/价值创造维度评估审计价值；上游整改结果，输出至管理层。"),
    (97, "case-library-update", "典型案例库更新", "audit.govern.case-library-update", "analysis",
     [C("distilled-result", "document")], [J("case-entry", "document")],
     "典型案例入库沉淀；上游审计成果，调用标签体系分类。"),
    (98, "issue-trend-analysis", "问题趋势分析", "audit.govern.issue-trend-analysis", "visualization",
     [C("history-issue-set", "finding-draft")], [J("trend-report", "metric-series")],
     "分析多期问题趋势/高发领域；上游历史问题库，调用可视化分析。"),
    (99, "rule-iteration", "规则库迭代优化", "audit.govern.rule-iteration", "governance",
     [C("trend-report", "metric-series")], [J("updated-rule-pack", "dataset-validation")],
     "基于审计发现更新审计规则/预警模型；上游问题趋势，⇠ 反向赋能风险扫描、问题定性、底稿校验。"),
    (100, "method-distill", "审计方法沉淀", "audit.govern.method-distill", "analysis",
     [C("project-review-input", "artifact")], [J("method-library", "document")],
     "沉淀优秀审计方法/技巧更新方法库；上游项目复盘，⇠ 反向赋能计划与实施阶段。"),
]

ALL = FOUNDATION + BUSINESS + GOVERN
