"""Graph-driven orchestration planning (M10): intent -> plan_only plan.

Breaks the "intent -> plan" dead link by treating the knowledge graph as the
semantic index for network orchestration.  A Chinese business intent is matched
deterministically (pg_trgm + bounded graph traversal, zero LLM/network) by a
replaceable ``CapabilityGraphPort`` implementation, the matched graph nodes are
resolved back to blueprint capability tokens through
``topology.blueprint_graph_links``, and the resulting plan_only plan is
generated by the existing ``TopologyService.plan()`` machinery (reused when the
deterministic ``plan_key`` already exists).  Every planning request is recorded
as an append-only ``topology.planning_intents`` evidence row, gated by
``topology.intent.plan`` (low / write_data, seeded inactive).
"""

from __future__ import annotations

import hashlib
from typing import Any, Protocol
from uuid import UUID, uuid4

import psycopg2
from psycopg2.errors import UniqueViolation
from psycopg2.extras import Json, register_uuid

from packages.policy.engine import PolicyEngine

from .contracts import PlanningIntentRequest
from .service import TopologyService

register_uuid()  # type: ignore[no-untyped-call]

_MAX_REQUIREMENTS = 32
_PLAN_BUDGET: dict[str, int] = {"max_candidates": 8, "max_chain_length": 8, "max_latency_ms": 3_000}
_PLANNER_VERSION = "1.0.0"


class CapabilityGraphPort(Protocol):
    """Replaceable deterministic graph matcher consumed by the planner.

    An embedding-backed matcher may be swapped in later without touching the
    planning flow; only ``match_nodes`` / ``expand_to_capabilities`` change.
    """

    def match_nodes(self, intent_text: str, max_matches: int = 4) -> list[dict[str, Any]]: ...

    def expand_to_capabilities(self, node_keys: list[str], expand_hops: int = 1) -> dict[str, Any]: ...


class GraphPlanningService:
    """Graph-driven plan_only planning behind the Policy gateway (M10)."""

    def __init__(
        self,
        database_url: str,
        topology_service: TopologyService,
        graph_port: CapabilityGraphPort,
        policy: PolicyEngine | None = None,
        tenant_slug: str = "local-dev",
    ) -> None:
        self.database_url = database_url
        self.topology_service = topology_service
        self.graph_port = graph_port
        self.policy = policy or PolicyEngine()
        self.tenant_slug = tenant_slug

    # -- helpers -------------------------------------------------------------

    def _tenant(self, cur: Any) -> UUID:
        cur.execute("SELECT id FROM iam.tenants WHERE slug=%s", (self.tenant_slug,))
        row = cur.fetchone()
        if row is None:
            raise ValueError(f"tenant not found: {self.tenant_slug}")
        tenant_id: UUID = row[0]
        cur.execute("SELECT set_config('app.tenant_id', %s, true)", (str(tenant_id),))
        cur.fetchone()
        return tenant_id

    def _gate(self, capability: str, arguments: dict[str, Any], *, risk_class: str = "medium") -> None:
        decision = self.policy.evaluate(capability, arguments, risk_class, side_effects="write_data")
        if decision.decision != "allow":
            raise PermissionError(f"policy denied {capability}: {decision.reason}")

    def _intent_replay(self, cur: Any, tenant_id: UUID, idempotency_key: str) -> dict[str, Any] | None:
        cur.execute(
            "SELECT id,intent_text,matched_nodes,capability_requirements,plan_key,trace_id,created_at "
            "FROM topology.planning_intents WHERE tenant_id=%s AND idempotency_key=%s",
            (tenant_id, idempotency_key),
        )
        row = cur.fetchone()
        if row is None:
            return None
        intent_id, intent_text, matched_nodes, requirements, plan_key, row_trace, created_at = row
        plan_summary = self._load_plan_summary(cur, tenant_id, plan_key=str(plan_key))
        cur.execute(
            "SELECT count(*) FROM topology.planning_intents "
            "WHERE tenant_id=%s AND plan_key=%s AND id<>%s",
            (tenant_id, plan_key, intent_id),
        )
        reused = bool(cur.fetchone()[0])
        return {
            "intent_id": str(intent_id),
            "intent_text": str(intent_text),
            "matched_nodes": [dict(item) for item in (matched_nodes if isinstance(matched_nodes, list) else [])],
            "capability_requirements": list(requirements) if isinstance(requirements, list) else [],
            "plan_key": str(plan_key),
            "mode": "plan_only",
            "plan_checksum": plan_summary["checksum"],
            "reused_plan": reused,
            "node_count": plan_summary["node_count"],
            "edge_count": plan_summary["edge_count"],
            "created_at": created_at.isoformat(),
            "trace_id": str(row_trace),
            "idempotent": True,
        }

    def _load_plan_summary(
        self, cur: Any, tenant_id: UUID, *, plan_key: str | None = None, mission_key: str | None = None
    ) -> dict[str, Any]:
        if plan_key is not None:
            cur.execute(
                "SELECT plan_key,checksum,plan_json FROM topology.routing_plans "
                "WHERE tenant_id=%s AND plan_key=%s",
                (tenant_id, plan_key),
            )
        elif mission_key is not None:
            cur.execute(
                "SELECT plan_key,checksum,plan_json FROM topology.routing_plans "
                "WHERE tenant_id=%s AND mission_key=%s ORDER BY created_at DESC LIMIT 1",
                (tenant_id, mission_key),
            )
        else:
            raise ValueError("_load_plan_summary requires plan_key or mission_key")
        row = cur.fetchone()
        if row is None:
            raise RuntimeError("referenced routing plan is missing; evidence cannot be reconstructed")
        payload = row[2] if isinstance(row[2], dict) else {}
        return {
            "plan_key": str(row[0]),
            "checksum": str(row[1]),
            "mode": "plan_only",
            "node_count": len(payload.get("nodes") or []),
            "edge_count": len(payload.get("edges") or []),
        }

    # -- intent -> plan flow -------------------------------------------------

    def plan_from_intent(self, request: PlanningIntentRequest | dict[str, Any], *, trace_id: UUID | None = None) -> dict[str, Any]:
        """Match a business intent to capability requirements and plan (plan_only).

        Steps: parse + Policy gate -> idempotent replay check -> deterministic
        graph matching -> bounded one-hop expansion -> blueprint link
        resolution -> fail-closed requirement check -> ``TopologyService.plan()``
        (reused on deterministic ``plan_key`` collision) -> append-only evidence
        row in ``topology.planning_intents``.
        """
        if isinstance(request, dict):
            request = PlanningIntentRequest.parse(request)
        trace_id = trace_id or request.trace_id or uuid4()
        self._gate("topology.intent.plan", {"intent": request.intent[:80]}, risk_class="low")
        with psycopg2.connect(self.database_url) as connection:
            with connection.cursor() as cur:
                tenant_id = self._tenant(cur)
                replay = self._intent_replay(cur, tenant_id, request.idempotency_key)
                if replay is not None:
                    return replay

                matched = self.graph_port.match_nodes(request.intent, int(request.budget["max_matches"]))
                expanded: list[dict[str, Any]] = []
                if int(request.budget["expand_hops"]) == 1:
                    expanded = self.graph_port.expand_to_capabilities(
                        [item["node_key"] for item in matched], 1
                    ).get("expanded", [])
                capability_nodes = self._capability_nodes(matched, expanded)
                requirements = self._resolve_requirements(cur, tenant_id, capability_nodes)
                if not requirements:
                    raise ValueError(
                        "intent matched no capability with a linked blueprint; planning rejected (fail-closed)"
                    )
                requirements = requirements[:_MAX_REQUIREMENTS]

                plan_response, caught_collision = self._plan_or_reuse(
                    cur, tenant_id, request, requirements, trace_id
                )
                row = self._record_intent(
                    cur, tenant_id, request, capability_nodes, requirements, plan_response, trace_id
                )
                intent_id, created_at = row
                cur.execute(
                    "SELECT count(*) FROM topology.planning_intents "
                    "WHERE tenant_id=%s AND plan_key=%s AND id<>%s",
                    (tenant_id, plan_response["plan_key"], intent_id),
                )
                count_row = cur.fetchone()
                reused = bool(count_row is not None and count_row[0]) or caught_collision
                return {
                    "intent_id": str(intent_id),
                    "intent_text": request.intent,
                    "matched_nodes": [dict(item) for item in capability_nodes],
                    "capability_requirements": list(requirements),
                    "plan_key": plan_response["plan_key"],
                    "mode": "plan_only",
                    "plan_checksum": plan_response["checksum"],
                    "reused_plan": reused,
                    "node_count": plan_response["node_count"],
                    "edge_count": plan_response["edge_count"],
                    "created_at": created_at.isoformat(),
                    "trace_id": str(trace_id),
                    "idempotent": False,
                }

    @staticmethod
    def _capability_nodes(matched: list[dict[str, Any]], expanded: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Merge direct matches with expanded nodes, carrying provenance.

        Direct matches keep their pg_trgm score and match kind; expanded nodes
        inherit the score of the matched node that reached them (recorded as
        ``source_node_key``) and are deduplicated against direct matches so a
        node never appears twice.  The result is ordered by (-score, node_key)
        so requirement ordering is deterministic.
        """
        score_by_key = {str(item["node_key"]): float(item.get("score") or 0.0) for item in matched}
        merged: dict[str, dict[str, Any]] = {}
        for item in matched:
            merged[str(item["node_key"])] = {
                "node_key": str(item["node_key"]),
                "space_key": str(item.get("space_key") or ""),
                "label": str(item.get("label") or ""),
                "node_type": str(item.get("node_type") or ""),
                "score": float(item.get("score") or 0.0),
                "match_kind": str(item.get("match_kind") or "direct"),
                "match_source": str(item.get("match_source") or "trigram"),
            }
        for item in expanded:
            key = str(item["node_key"])
            if key in merged:
                continue
            merged[key] = {
                "node_key": key,
                "space_key": str(item.get("space_key") or ""),
                "label": str(item.get("label") or ""),
                "node_type": str(item.get("node_type") or "capability"),
                "score": score_by_key.get(str(item.get("source_node_key") or ""), 0.0),
                "match_kind": "expanded",
                "match_source": str(item.get("match_source") or "bridge"),
                "source_node_key": str(item.get("source_node_key") or ""),
            }
        ordered = sorted(merged.values(), key=lambda item: (-item["score"], item["node_key"]))
        return [{"score": round(item["score"], 6), **item} for item in ordered]

    def _resolve_requirements(
        self, cur: Any, tenant_id: UUID, capability_nodes: list[dict[str, Any]]
    ) -> list[str]:
        """Map matched capability nodes to blueprint capability tokens.

        Only ``capability`` nodes participate; domain nodes are evidence only.
        Requirements are ordered by the deterministic node ordering and
        deduplicated (a capability token is never emitted twice).
        """
        capability_keys = [item["node_key"] for item in capability_nodes if item.get("node_type") == "capability"]
        if not capability_keys:
            return []
        cur.execute(
            "SELECT node_key,blueprint_key FROM topology.blueprint_graph_links "
            "WHERE tenant_id=%s AND node_key=ANY(%s)",
            (tenant_id, capability_keys),
        )
        link_map = {str(row[0]): str(row[1]) for row in cur.fetchall()}
        if not link_map:
            return []
        blueprint_keys = sorted({key for key in link_map.values() if key})
        if not blueprint_keys:
            return []
        cur.execute(
            "SELECT key,capability_contract->>'capability' FROM topology.plugin_blueprints "
            "WHERE tenant_id=%s AND key=ANY(%s)",
            (tenant_id, blueprint_keys),
        )
        capability_by_blueprint = {str(row[0]): str(row[1]) for row in cur.fetchall() if row[1]}
        requirements: list[str] = []
        seen: set[str] = set()
        for item in capability_nodes:
            if item.get("node_type") != "capability":
                continue
            node_key = item.get("node_key")
            if node_key is None:
                continue
            capability = capability_by_blueprint.get(link_map.get(str(node_key)) or "")
            if not capability or capability in seen:
                continue
            seen.add(capability)
            requirements.append(capability)
        return requirements

    def _plan_or_reuse(
        self,
        cur: Any,
        tenant_id: UUID,
        request: PlanningIntentRequest,
        requirements: list[str],
        trace_id: UUID,
    ) -> tuple[dict[str, Any], bool]:
        """Delegate to ``TopologyService.plan()``; reuse on deterministic plan_key collision.

        The plan idempotency key is derived from the intent key and the
        requirement set so identical intents always replay the same plan row
        even across distinct intent keys.  When the deterministic ``plan_key``
        already exists (UNIQUE(tenant_id, plan_key)), the previously built plan
        is loaded and returned with ``reused_plan=True``.
        """
        derived_key = "m10-graph-plan:" + hashlib.sha256(
            (request.idempotency_key + "|" + "|".join(requirements)).encode("utf-8")
        ).hexdigest()
        plan_payload: dict[str, Any] = {
            "intent": request.intent,
            "idempotency_key": derived_key,
            "mode": "plan_only",
            "capability_requirements": list(requirements),
            "budget": dict(_PLAN_BUDGET),
            "planner_version": _PLANNER_VERSION,
            "trace_id": str(trace_id),
        }
        caught_collision = False
        try:
            plan_response = self.topology_service.plan(plan_payload)
        except UniqueViolation:
            caught_collision = True
            plan_response = self._load_plan_summary(
                cur, tenant_id, mission_key="|".join(requirements)
            )
        return plan_response, caught_collision

    def _record_intent(
        self,
        cur: Any,
        tenant_id: UUID,
        request: PlanningIntentRequest,
        capability_nodes: list[dict[str, Any]],
        requirements: list[str],
        plan_response: dict[str, Any],
        trace_id: UUID,
    ) -> tuple[Any, Any]:
        """Append the planning-intent evidence row (INSERT only)."""
        cur.execute(
            """INSERT INTO topology.planning_intents
            (tenant_id,intent_text,matched_nodes,capability_requirements,plan_key,trace_id,idempotency_key,reason)
            VALUES(%s,%s,%s,%s,%s,%s,%s,%s)
            RETURNING id, created_at""",
            (
                tenant_id,
                request.intent,
                Json([dict(item) for item in capability_nodes]),
                Json(list(requirements)),
                plan_response["plan_key"],
                str(trace_id),
                request.idempotency_key,
                request.reason,
            ),
        )
        row = cur.fetchone()
        if row is None:
            raise RuntimeError("planning intent insert returned no id")
        return row[0], row[1]

    # -- read-only projections ------------------------------------------------

    def list_intents(self, limit: int = 50) -> list[dict[str, Any]]:
        with psycopg2.connect(self.database_url) as connection:
            with connection.cursor() as cur:
                self._tenant(cur)
                cur.execute(
                    """SELECT id,intent_text,capability_requirements,plan_key,trace_id,created_at
                    FROM topology.planning_intents ORDER BY created_at DESC LIMIT %s""",
                    (limit,),
                )
                return [
                    {
                        "intent_id": str(row[0]),
                        "intent_text": str(row[1]),
                        "capability_requirements": list(row[2]) if isinstance(row[2], list) else [],
                        "plan_key": str(row[3]),
                        "trace_id": str(row[4]),
                        "created_at": row[5].isoformat(),
                    }
                    for row in cur.fetchall()
                ]

    def get_intent(self, intent_id: UUID) -> dict[str, Any]:
        with psycopg2.connect(self.database_url) as connection:
            with connection.cursor() as cur:
                tenant_id = self._tenant(cur)
                cur.execute(
                    """SELECT id,intent_text,matched_nodes,capability_requirements,plan_key,trace_id,created_at
                    FROM topology.planning_intents WHERE id=%s""",
                    (intent_id,),
                )
                row = cur.fetchone()
                if row is None:
                    raise ValueError(f"planning intent not found: {intent_id}")
                intent_id, intent_text, matched_nodes, requirements, plan_key, row_trace, created_at = row
                plan_summary = self._load_plan_summary(cur, tenant_id, plan_key=str(plan_key))
                cur.execute(
                    "SELECT count(*) FROM topology.planning_intents "
                    "WHERE tenant_id=%s AND plan_key=%s AND id<>%s",
                    (tenant_id, plan_key, intent_id),
                )
                reuse_count = cur.fetchone()
                reused = bool(reuse_count is not None and reuse_count[0])
                return {
                    "intent_id": str(intent_id),
                    "intent_text": str(intent_text),
                    "matched_nodes": [dict(item) for item in (matched_nodes if isinstance(matched_nodes, list) else [])],
                    "capability_requirements": list(requirements) if isinstance(requirements, list) else [],
                    "plan_key": str(plan_key),
                    "mode": "plan_only",
                    "plan_checksum": plan_summary["checksum"],
                    "reused_plan": reused,
                    "node_count": plan_summary["node_count"],
                    "edge_count": plan_summary["edge_count"],
                    "created_at": created_at.isoformat(),
                    "trace_id": str(row_trace),
                    "idempotent": False,
                }
